version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Listing project root:"
      - ls -R
      - sam build
      - sam deploy --stack-name multi-lambda-stack --region us-east-1 --s3-bucket for-upload-pipelineus-east-1-d4e665bfbf45 --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset
