version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Listing project root:"
      - ls -R
      - sam build
      - sam deploy --stack-name multi-lambda-stack \
          --s3-prefix multi-lambda-stack \
          --s3-bucket codepipeline-us-east-1-d4e665bfbf45-4909-8df2-a6ef250f3f62 \ 
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --region us-east-1 \
          --no-fail-on-empty-changeset
