version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
    build:
    commands:
      - echo Packaging Lambda function...
      - zip -r lambda.zip . -x "*.git*" "*__pycache__*" "*.pytest_cache*" "app/*"
  post_build:
    commands:
      - echo Deploying to AWS Lambda...
      - aws lambda update-function-code --function-name fybo.py --zip-file fileb://lambda.zip 

artifacts:
  files:
    - lambda.zip