version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Listing project root:"
      - ls -R
      - sam build
      - sam package \
          --template-file template.yaml \
          --s3-bucket codepipeline-us-east-1-d4e665bfbf45-4909-8df2-a6ef250f3f62 \ 
          --output-template-file packaged.yaml
          
       - sam deploy \
          --template-file packaged.yaml \
          --stack-name multi-lambda-stack \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset