AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FunctionOne:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: function-one
      CodeUri: ./function-one
      Handler: function-one.lambda_handler
      Role: arn:aws:iam::730335455538:role/function-one
      Runtime: python3.11
      MemorySize: 128
      Timeout: 10

