AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FunctionOne:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: functionOne
      CodeUri: /
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 10

